trigger:
- "*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  x: 10
  name: 'John'
  n: $[length(variables.name)]

steps:
- task: CmdLine@2
  displayName: "Print variables"
  inputs:
    script: |
        echo $(x)
        echo $(name)
        echo $(n)
  condition: not(eq(variables.x, 20))

