trigger:
- "*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  x: 10
  y: 20
  name: 'john' 

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
        echo "$(x)"            # 10

