trigger:
- "*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  y: $(Build.BuildID)

steps:
- task: CmdLine@2
  displayName: "Print variables"
  inputs:
    script: |
        echo $(Build.BuildID)
        echo $(y)
  condition: not(eq(variables.Build.BuildID, 10))

