trigger:
- "*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  name: 'john' 
  n1: $[length(variables.name)]    # length of string
  friends:
  - 'john'
  - 'maria'
  - 'fido'
  n2: $[length(variables.friends)] # length of list

steps:
- task: Bash@3
  displayName: Say Hello To $(name)   # variable in attribute
  inputs:
    targetType: 'inline'
    script: |
        echo "Hello $(name)"                   # variable in script
        echo "Your name is $(n1) letters long."
  condition: | # variable in function
    and (
        succeeded(),
        eq(variables['Build.SourceBranchName'], 'demo')
    ) 

